language: node_js
node_js
- 0.10
notifications:
  email: false
services:
- mongodb
env:
  global:
    - NODE_ENV: production
before_install:
- npm install -g bower
- npm install -g gulp
- npm install -g stylus
- bower install
before_script:
- gulp
